### ISSUE TITLE
strongly agree is red

### ISSUE THREAD

**Issue by pvinis** [StateOfJS/StateOfJS-2020#14]
the color should be flipped in "opinions". strongly agree should be green and disagree red.

**Comment by lloydjatkinson** [comment]
Yes, I was extremely confused for a good amount of time reading the survey till I noticed the colours are the wrong way around.


![image](https://user-images.githubusercontent.com/5633938/104449597-bb413400-5596-11eb-89bb-dec5855f9c27.png)

**Comment by SachaG** [comment]
Fixing it now.
