### ISSUE TITLE
TypeScript appears twice in the Satisfaction vs Usage graph

### ISSUE THREAD

**Issue by tranvansang** [StateOfJS/StateOfJS-2020#17]
https://2020.stateofjs.com/en-US/technologies/

![image](https://user-images.githubusercontent.com/13043196/104424684-0e30e080-55c3-11eb-9418-830a442fdee4.png)
![image](https://user-images.githubusercontent.com/13043196/104424698-12f59480-55c3-11eb-92cc-bd96762a6eeb.png)
![image](https://user-images.githubusercontent.com/13043196/104424797-2ef93600-55c3-11eb-94d6-030c0644ea61.png)

**Comment by SachaG** [comment]
Yes, one is the language and one is the build tool. I'll add a note to clarify this, thanks!
