### ISSUE TITLE
Shadow DOM description is duplicate of Custom Elements

### ISSUE THREAD

**Issue by TimboTambo** [StateOfJS/StateOfJS-2020#19]
`Shadow DOM` description in `BrowserAPIs` section uses duplicate description to `Custom Elements`:

> Web Components is a suite of different technologies allowing you to create reusable custom elements — with their functionality encapsulated away from the rest of your code — and utilize them in your web apps.

**Comment by SachaG** [comment]
This is because they both share a page on MDN. Maybe I'll change it, let me see.
