### ISSUE TITLE
Typo in the Russian translation (in intro written about css).

### ISSUE THREAD

**Issue by fromnt34** [StateOfJS/StateOfJS-2020#31]
![Снимок экрана (128)](https://user-images.githubusercontent.com/60347317/104609765-700d4b00-5694-11eb-9aa9-b8c28d23aa54.png)

In the English version it is written as follows: "And now, let's see what ***JavaScript*** has been up to this year!" (in Russian it will be translated as: "А теперь давайте посмотрим, каким был ***JavaScript*** в этом году!").

But in the Russian version it is translated as: "А теперь давайте посмотрим, каким был ***CSS*** в этом году!" (in English it will be translated as: "And now, let's see what ***CSS*** has been up to this year!").

**Comment by SachaG** [comment]
cc @lex111
