### ISSUE TITLE
Theme changes when typing `x`

### ISSUE THREAD

**Issue by MaxAltena** [StateOfJS/StateOfJS-2020#37]
![CleanShot 2021-01-16 at 14 59 14](https://user-images.githubusercontent.com/28545135/104813772-825dc500-580b-11eb-8ec6-0c5d8b982de3.gif)

When leaving my email, the theme kept changing when I typed the `x` key.

**Comment by SachaG** [comment]
Oh that's annoying, sorry… it's a featured we added for our own internal debugging but we should remove it in production!

**Comment by MaxAltena** [comment]
Closed through #38
