### ISSUE TITLE
I feel bad it has "Race & Ethnicity"

### ISSUE THREAD

**Issue by Nek-** [StateOfJS/StateOfJS-2020#5]
Hello,

Let spread some context first.

![Screenshot_20201207-140211__01](https://user-images.githubusercontent.com/972456/101470036-c5439780-3945-11eb-92af-f7e563e907ff.jpg)

I have many "racial" (god I freaking hate this word) origins. At first gland, I tried to just ignore there was this question about the race. But sorry, I can't just say nothing. To me, this question is highly offensive.

I understand having stats on how people see javascript by country. It's even fine by sex (even if some may complain because blah blah blah non-binary blah stuff), but we all know that it's a world of men, and having some stats about the state of javascript for women may be interesting (I actually do not really think it's really useful or what, just acceptable to me).

Getting statistics of the javascript world based on a "race", god, it hurts. For many reasons : 

1. All human is equaled no matter its "race", or maybe should I say race doesn't even exist
2. It can't give eventually good result: some people will be offended just like me and will just not answer, some other will answer a "race" but nothing geographical here, to me it just makes no sense
3. The result of "race" for javascript does not make any sense (will you get something positive from that eventual result ?)
4. You forgot so many people! Here the answer is basically "u black slave or kind white eu", god there's so much more diversity. Of course, you will hurt people just with this situation!

To conclude, maybe you understand aggressivity here, there's not. I just wanted to write something about it so you know not everybody is fine with it.

I obviously suggest removing this question (with no real expectation since I'm nobody and it seems that I'm the only one offended). I think you should at least answer to this post so people learn about your goal for it.

**Comment by SachaG** [comment]
I don't think this really merits a full response as it seems like a very naive and uninformed view, but I do want to point out that saying "race does not exist" is extremely privileged and negates the experience of many, many people who have a different view. 

I welcome debate on this complex question but it requires being a little more informed first, sorry.
