### ISSUE TITLE
Issue link in footer broken

### ISSUE THREAD

**Issue by Ryuno-Ki** [StateOfJS/StateOfJS-2020#7]
https://survey.stateofjs.com/$https://github.com/StateOfJS/StateOfJS-Vulcan/issues is recursively appending the wrong URL.

See hover link in the bottom of
![stateofjs](https://user-images.githubusercontent.com/3097194/101680255-b6053c80-3a60-11eb-9bc5-4ba06ff75601.png)

**Comment by SachaG** [comment]
Thanks! I'll close this as a duplicate but I'm aware of the issue.
